### ISSUE TITLE
Little benchmark proof that this implementation is faster

### ISSUE THREAD

**Issue by adriens** [osiegmar/FastCSV#1]
Hi, i'm looking for a fast csv writer java lib, in append mode.
I've discovered your lib and i wonder if you have some benchmark/proof that your implementation is faster than others...like apache commons for example (http://commons.apache.org/proper/commons-csv/) ?

Thanks in advance for your answer.

Regards,

**Comment by osiegmar** [comment]
Thanks for your very legitimate question! Of course, I did benchmarks but didn't make them public available -- until now: https://github.com/osiegmar/JavaCsvBenchmarkSuite

**Comment by adriens** [comment]
Hi, this is great !!! Thanks a lot for your answer...as what i needed was to write fast 😸 

Have a nice week.

Kind regards,

Adrien
