### ISSUE TITLE
OSGi support

### ISSUE THREAD

**Issue by stbischof** [osiegmar/FastCSV#102]
**Is your feature request related to a problem? Please describe.**
I want to use this lib in an OSGi Framework. Therefor the MANIFEST.MF needs Bundle Metadata.

**Describe the solution you'd like**
Let bnd add all relevant Metadata(Bundle-SymbolicName , BundleVersion and Exports)
https://github.com/bndtools/bnd/blob/master/gradle-plugins/README.md

**Describe alternatives you've considered**
bad quality metadata by writing it by hand.

**RFC 4180 compliance**
nope

```
Bundle-SymbolicName: de.siegmar.fastcsv
Bundle-Version: 2.2.2
Export-Package: de.siegmar.fastcsv.reader;version="2.2.2",de.siegmar.f
 astcsv.writer;version="2.2.2"
Import-Package: java.io,java.lang,java.lang.invoke,java.nio.charset,ja
 va.nio.file,java.util,java.util.function,java.util.stream
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
```

**Comment by osiegmar** [comment]
OSGi support was already added to the develop branch by https://github.com/osiegmar/FastCSV/pull/89 and https://github.com/osiegmar/FastCSV/pull/92. Release of version 3 will follow very soon.

```
Manifest-Version: 1.0
Bnd-LastModified: 1703510660755
Bundle-ManifestVersion: 2
Bundle-Name: de.siegmar.fastcsv
Bundle-SymbolicName: de.siegmar.fastcsv
Bundle-Version: 3.0.0.SNAPSHOT
Created-By: 21.0.1 (Eclipse Adoptium)
Export-Package: de.siegmar.fastcsv.reader;version="3.0.0",de.siegmar.f
 astcsv.writer;version="3.0.0"
Import-Package: java.io,java.lang,java.lang.invoke,java.nio,java.nio.c
 hannels,java.nio.charset,java.nio.file,java.util,java.util.concurrent
 .atomic,java.util.function,java.util.stream
Private-Package: de.siegmar.fastcsv.util
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=11))"
Tool: Bnd-7.0.0.202310060912
```
