### ISSUE TITLE
Limits should be overridable default values

### ISSUE THREAD

**Issue by stbischof** [osiegmar/FastCSV#104]
Hi,

i think that the Limits are good default values, bit would be nice to make them changeable.

https://github.com/osiegmar/FastCSV/blob/f618bc6e59a9d04570bafa1d86b2228eba878c7a/lib/src/main/java/de/siegmar/fastcsv/reader/AbstractCsvCallbackHandler.java#L95

**Comment by osiegmar** [comment]
Sounds reasonable. I'd be glad if someone could come up with a pull request.

**Comment by osiegmar** [comment]
@stbischof Does #112 address your request sufficiently (esp. regarding OSGi compatibility)?

**Comment by stbischof** [comment]
This is very nice. Thank you.
