### ISSUE TITLE
CSV to Bean support

### ISSUE THREAD

**Issue by BigChief45** [osiegmar/FastCSV#11]
Similar to OpenCSV's [CsvToBeanBuilder](http://opencsv.sourceforge.net/apidocs/com/opencsv/bean/CsvToBeanBuilder.html)

**Comment by osiegmar** [comment]
For the sake of simplicity (and small footprint), I decided not to add this kind of functionality. Think of FastCSV as a low-level CSV implementation designed for performance. Everything else could be build on top it.
