### ISSUE TITLE
[Document only] Update `Declare dependency` section of the `quickstart.mdx`

### ISSUE THREAD

**Issue by saiya** [osiegmar/FastCSV#113]
**Describe the bug**

["Declare dependency" section of the `quickstart.mdx`](https://github.com/osiegmar/FastCSV/blob/9a7e6df64dc17ac2ab9e76d0661666f0d87bb20d/docs/src/content/docs/guides/quickstart.mdx?plain=1#L13-L44) looks not pointing latest group ID of the FastCSV artifact.

As that document linking to the https://central.sonatype.com/artifact/de.siegmar/fastcsv , correct group ID looks `de.siegmar` instead of the `com.github.osiegmar`.

**To Reproduce**

Add dependency as in the document:
```
implementation("com.github.osiegmar:fastcsv:3.2.0") // Does not work
```

Adding this dependency works well:

```
implementation("de.siegmar:fastcsv:3.2.0") // Works fine
```

**Additional context**

I searched around CSV libraries and found this library has excellent quality, and tried to use this.

Thank you for maintaining this good library; hoping this small change helps other pepole to start using this library more smoothly.

**Comment by osiegmar** [comment]
Thanks for pointing this out!
