### ISSUE TITLE
MalformedCsvException: Row 222 has 2 fields, but first row had 1 fields

### ISSUE THREAD

**Issue by cptjackwu** [osiegmar/FastCSV#120]
NamedCsvReader.builder().build(reader).forEach(v -> {
                mapList.add(v.getField(key));
            });

I want it to skip the line that reports an error, and instead of reporting an error, let the program go down

jdk1.8

**Comment by osiegmar** [comment]
This was a design decision for version 2 of FastCSV. Followed by #78 and #87, this feature has been implemented as part of version 3.

In version 3 this would work:

```java
CsvReader.builder().ofNamedCsvRecord(reader)
    .forEach(r -> mapList.add(r.getField(key)));
```
