### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by gidravlic** [osiegmar/FastCSV#13]
Hello i have problem using CsvReader:
Csv file:
Field1	Field2	Field3	Field4	Field5
1Value1	1Value2	1Value3	1Value4	1Value5
2Value1	2Value2	2Value3	2Value4	2Value5
3Value1	3Value2	3Value3	3Value4	3Value5
Simple program:
```java
CsvReader reader = new CsvReader();
reader.setTextDelimiter('\t');
reader.setContainsHeader(true);
CsvContainer csv = reader.read(Paths("test.csv"), StandardCharsets.UTF_8);
for (CsvRow row : csv.getRows()) {
     System.out.println(row);
     System.out.println(row.getField(0));
     System.out.println(row.getField(1));
}
```
Output:
CsvRow{originalLineNumber=2, fields={Field1	Field2	Field3	Field4	Field5=1Value1	1Value2	1Value3	1Value4	1Value5}}
1Value1	1Value2	1Value3	1Value4	1Value5
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at de.siegmar.fastcsv.reader.CsvRow.getField(CsvRow.java:66)
	at org.mycompany.fastcsvtest.Main.readTest(Main.java:92)
	at org.mycompany.fastcsvtest.Main.main(Main.java:28)

Any thoughts?
Thanks.

**Comment by gidravlic** [comment]
Errorline is at: System.out.println(row.getField(1));
Thanks for the advice. I'll check it again and I'll write UnitTest tomorrow.

**Comment by osiegmar** [comment]
Yes -- configured field separator does not match the file.
