### ISSUE TITLE
ArrayIndexOutOfBoundsException And Null when reading from getField

### ISSUE THREAD

**Issue by extstmtrifork** [osiegmar/FastCSV#17]
Hi, 

I have a problem using the csvReader. 
I have created the csv file using the full csv at once writer including header and custom settings as 
`csvWriter.setFieldSeparator(';');`
`csvWriter.setLineDelimiter("\r\n".toCharArray());`
`csvWriter.setAlwaysDelimitText(true);`

However i am trying to read the csv file using the full CSV file with header at once reader. 
At first my issue is i get an ArrayIndexOutOfBoundException, and i dont know if this is caused by a large csv file. 
`public Map<String, String> readingFileAtOnceHeader(File file) throws IOException {`
        ` Map<String, String> personMap = new HashMap<>();`
        `CsvReader csvReader = new CsvReader();`
        `csvReader.setContainsHeader(true);`
        `CsvContainer csv = csvReader.read(file, StandardCharsets.UTF_8);`
        `for (CsvRow row : csv.getRows()) {`
            `personMap.put(row.getField("PersonID"), row.getField("CivilRegistrationNumber"));`
        `}`
        `return personMap;`
    `}`
Then i tried to add 
`csvReader.setTextDelimiter('\'');`
which solved the problem (However this is not what i want to add).

The second issue is that i am trying to read the two of the header fields, as illustrated in the above code. However both of these a null and i cant figure out why. I tried with index as well, and when i try
`row.getField(0)` 
it returns the whole row of data and not only data at index 0. While 
`row.getField(0)`
return an indexOutOfBoundException.

**Comment by osiegmar** [comment]
I can't answer your questions without knowing the CSV file. I assume, that your configuration (text delimiter, field separator) does not match the CSV file format.

Could you also please provide a full stacktrace of the ArrayIndexOutOfBounceException you mentioned?

**Comment by osiegmar** [comment]
If you like, just reopen the ticket with further information...
