### ISSUE TITLE
CSV appender for writting big files

### ISSUE THREAD

**Issue by josevi86** [osiegmar/FastCSV#18]
I want to create a big csv file using the CSV Appender. I'm using this code:

    `for (int i = 0; i < writeBuffer.size(); i++) {
		String array[] = writeBuffer.get(i).toArray(new String[writeBuffer.get(i).size()]);
		csvAppender.appendLine(array);
       }`

being writeBuffer a List<List<String>>. This buffer can have more than 500 lines.
When I finish with the processing, the resulting file only has 148 lines and the last one is incomplete.

I also have try to flush at 100 lines, but then is not writting the next lines.

Maybe i am using the library in a incorrect way?

Thanks in advance.

**Comment by osiegmar** [comment]
You can use appendLine() or a combination of one (or multiple) appendField() and endLine() to append data to the output. The output (e.g. the file) will be closed when closing the CsvAppender (either by explicitly calling close() or implicitly by using try-with-resources).

**Comment by Pascal66** [comment]
Happen to me too. 
With or without endline()

The strange thing happen when I append a field with a Double and not with an Integer.

    csvAppenderTrain.appendField("7"); //WORK
    csvAppenderTrain.appendField("7.0"); //NOT WORKING
