### ISSUE TITLE
Please make compatible for Kotlin 

### ISSUE THREAD

**Issue by thaw-frobom** [osiegmar/FastCSV#25]
I faced error when using this with kotlin for android version of 23. I found that android remove many class like java.time and java.nio. Can you fix this incompatible.

**Comment by osiegmar** [comment]
What I can tell from issue #3 is, that FastCSV is supported by Android 8.0 (and partially by Android 7.0). API version 23 is Android 6.0, which seems to be too old to support a Java 7 library.

Please note, that FastCSV does not claim any Android support but Java 7.0 support.
