### ISSUE TITLE
Option to set null string?

### ISSUE THREAD

**Issue by revyTH** [osiegmar/FastCSV#33]
Null string default is written as "null". Should be present a setter to override the default null string

**Comment by osiegmar** [comment]
FastCSV writes a null string as an empty field, not as "null".

```
try (CsvAppender csv = new CsvWriter().append(new PrintWriter(System.out))) {
    csv.appendLine("foo", null, "bar");
}
```

prints: `foo,,bar`

If you want to transform null to some other value, why pass null to FastCSV?
