### ISSUE TITLE
Per-field quoting

### ISSUE THREAD

**Issue by metametadata** [osiegmar/FastCSV#39]
I need a way to enforce per-field quoting in order to generate CSV for PostgreSQL COPY statement because quoted empty string is treated as NULL, while totally empty field is treated as an empty string:

```
1,,3 ---> ""
1,"",3 ---> NULL
```

The current `CsvAppender` API doesn't support such behavior. Possible solutions:

* add an additional flag to `appendField`
* add a new method `appendDelimitedField`
* make `alwaysDelimitText` field mutable so that the consumer can turn it off/on before appending the specific field

**Comment by osiegmar** [comment]
According to https://www.postgresql.org/docs/current/sql-copy.html you can use `\N` (or other value with the `NULL AS` clause) to differentiate between empty and null fields.

**Comment by metametadata** [comment]
Yes, I'm using "NULL AS" as a workaround (`\N` is for text format, not CSV). The drawback of this workaround is that the sentinel null string cannot be used in the CSV as a real value anymore.

**Comment by osiegmar** [comment]
OK, understood. But your example is mixed up, I think. According to the doc, an unquoted empty string is handled as `NULL`, not a quoted one. So, what you would need is:

```
1,,3 ---> NULL
1,"",3 ---> ""
```
Is that correct?

**Comment by metametadata** [comment]
Ah, yes, you're right.

**Comment by osiegmar** [comment]
I consider this for the 2.0 release. Could you please check the commit faac27111e5acd183b0c09471b24ea8b50f35f23 to see if it covers your requirements. I don't think that a per field setting is required, though.

**Comment by metametadata** [comment]
Yes, looks like it will do the trick.

**Comment by osiegmar** [comment]
Implemented in version 2.
