### ISSUE TITLE
To flush, or not to flush?

### ISSUE THREAD

**Issue by Jokero** [osiegmar/FastCSV#4]
I noticed that `FastBufferedWriter` has `flush` method which is never called:
```java
// https://github.com/osiegmar/FastCSV/blob/master/src/main/java/de/siegmar/fastcsv/writer/FastBufferedWriter.java#L70-L73
@Override
public void flush() throws IOException {
    flushBuffer();
    out.flush();
}
```

`FastBufferedWriter` uses `flushBuffer`:
```java
@Override
public void write(final char[] cbuf, final int off, final int len) throws IOException {
    if (pos + len >= buf.length) {
        flushBuffer();
    }

    if (len >= buf.length) {
        out.write(cbuf, off, len);
    } else {
        System.arraycopy(cbuf, off, buf, pos, len);
        pos += len;
    }
}

private void flushBuffer() throws IOException {
    out.write(buf, 0, pos);
    pos = 0;
}
```
Should `FastBufferedWriter` use `flush` instead of `flushBuffer`? Or what is the purpose of `flush` and when it should be used? Readme does not provide any information about it

**Comment by osiegmar** [comment]
The class `FastBufferedWriter` is used internally by `CsvAppender`. The `flush` method actually **is** invoked via the `flush` method of `CsvAppender` -- both are implementing the `Flushable` interface. Whether or not you need to flush data without closing the stream depends on your use case (as it is always the case with all implementations of `Flushable`). In doubt you don't need it.

The `flushBuffer` method is only used to flush the internal buffer within `FastBufferedWriter`. The intention was not to flush to the underlying stream/writer.
