### ISSUE TITLE
Disable delimiter for new line / textDelimiter

### ISSUE THREAD

**Issue by larsmathuseck** [osiegmar/FastCSV#41]
I cannot find any option to disable the textDelimiter.
Any idea?

**Comment by osiegmar** [comment]
That is not possible. As [RFC 4180](https://tools.ietf.org/html/rfc4180) says:

> Each record is located on a separate line, delimited by a line break (CRLF)

and

> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.

What is your use case?

**Comment by larsmathuseck** [comment]
Thanks for your fast answer.

As in RFC:

>    6.  Fields containing line breaks (CRLF), double quotes, and commas
>        should be enclosed in double-quotes.  For example:
> 
>        "aaa","b CRLF
>        bb","ccc" CRLF
>        zzz,yyy,xxx

I think it is only important to quote when your fields contain line breaks (CRLF), double quotes, or commas.

I wanted to disable the double quotes, because it seems unnecessary and can cause trouble importing the recorded data in pythons pandas.

**Comment by osiegmar** [comment]
> I think it is only important to quote when your fields contain line breaks (CRLF), double quotes, or commas.

But exactly this is done by FastCSV if you did not enable the `alwaysDelimitText` option.

If you have a different experience, could you show some example code please?
