### ISSUE TITLE
When are you planning to release v2?

### ISSUE THREAD

**Issue by HerbCSO** [osiegmar/FastCSV#42]
Sorry, this is probably not the best forum for this question, but I'm not quite sure where else to ask this - feel free to point me somewhere else for this discussion.

I see a number of references to a v2 which will probably introduce a number of improvements but also breaking changes. When are you thinking you might be releasing a v2? I see some commits from January in the `version2-rewrite` branch, but can't quite get a sense of how far along you are with that.

Also, it looks like v2 will [require Java 8](https://github.com/osiegmar/FastCSV/commit/5026f8dd3ee8fabef4b70d01cae5df121e8d49d4#diff-04c6e90faac2675aa89e2176d2eec7d8R39) - is that correct?

**Comment by osiegmar** [comment]
I definitely want to release a v2 at some point in the future. Unfortunately I currently don't have the time for that and don't know when that'll be.

**Comment by HerbCSO** [comment]
Understandable. Thanks for answering though! ;]
