### ISSUE TITLE
Any plans to make a release?

### ISSUE THREAD

**Issue by nikarh** [osiegmar/FastCSV#47]
Hi, there are commits in master, but no releases were made in two years, is it possible for you to make a release?
Specifically interested in the following [fix](https://github.com/osiegmar/FastCSV/commit/474de29e55e3626475d3069d86b5319df5689bc3).

Thanks!

**Comment by osiegmar** [comment]
Version [1.0.4](https://github.com/osiegmar/FastCSV/releases/tag/v1.0.4) is released. This is the last planned release before version 2.
