### ISSUE TITLE
Unable to contact via email

### ISSUE THREAD

**Issue by expertdev2020** [osiegmar/FastCSV#54]
Hi,

I'm a java programmer and saw the statistics and it was awesome. I have used CSV reader as well.

How does it works very fast? Which change makes it very fast and missing in other libraries?

I'm very curious to know..Since i am unable to find the email address..putting as feature request. Please don't mistake.

Thanks

**Comment by osiegmar** [comment]
> How does it works very fast? Which change makes it very fast and missing in other libraries?

For the reader: https://github.com/osiegmar/FastCSV/blob/v2.0.0/src/main/java/de/siegmar/fastcsv/reader/RowReader.java
...the rather optimized code for reading, buffering and materializing of strings

For the writer: https://github.com/osiegmar/FastCSV/blob/v2.0.0/src/main/java/de/siegmar/fastcsv/writer/CsvWriter.java
...it's mainly about the optimized buffering and detection of the need of quotation
