### ISSUE TITLE
How to append a row to an existing file?

### ISSUE THREAD

**Issue by villain-bryan** [osiegmar/FastCSV#56]
Maybe I'm missing something obvious .. I want to simply add a row of data to a CSV file that already exists on disk.

Using CsvWriter and writeRow does not create a row at the bottom of the file. I noticed things changed in the version overhaul, and the CsvAppender and appendLine stuff is gone.

So, using the CsvWriter how can you open an existing CSV file and add a row of new data?

**Comment by osiegmar** [comment]
Simply use the OpenOptions of `CsvWriterBuilder#build(Path, Charset, OpenOption...)` for that.

Example:

```
try (CsvWriter csv = CsvWriter.builder().build(path, StandardCharsets.UTF_8, StandardOpenOption.APPEND)) {
    csv.writeRow("value1", "value2");
}
```

**Comment by villain-bryan** [comment]
Not sure how I missed that. Thank you @osiegmar
