### ISSUE TITLE
Unnecesary temporary objects in CsvAppender

### ISSUE THREAD

**Issue by qtxo** [osiegmar/FastCSV#8]
In CsvAppender.appendField(final String value)
```
final char[] valueChars = value.toCharArray();
...
for (final char c : valueChars) {
```
This is creating a temporary array that is only used to be iterated. It is easy to avoid this:
```
for (int i = 0; i < value.length(); i++) {
    final char c = value.charAt(i);
``` 
IMO the extra index checks in charAt() weight less than the "new char[length]" impact on GC. Maybe I am wrong.

BTW, thanks for this nice easy to use library!

**Comment by osiegmar** [comment]
You're right. Thanks for pointing this out! Could you provide a pull request?
