### ISSUE TITLE
Unnecessary "throws IOException" in  CsvParser.parse()

### ISSUE THREAD

**Issue by qtxo** [osiegmar/FastCSV#9]
You can remove the throws because there is nothing that can throw the exception.

```
public CsvParser parse(final Reader reader) / * nothing happens without throws IOException */{
        return new CsvParser(Objects.requireNonNull(reader, "reader must not be null"),
            fieldSeparator, textDelimiter, containsHeader, skipEmptyRows,
            errorOnDifferentFieldCount);
    }
```

**Comment by osiegmar** [comment]
Thanks, I know. I will change that in a new major version, because this will break compatibility.

**Comment by qtxo** [comment]
You can add a new method and deprecate this onw, no?

**Comment by osiegmar** [comment]
All the parse methods are overloaded. I'd like to keep it that way (without adding a new one with the same functionality but a different name). FastCSV 2.0 will simply have this changed...

**Comment by osiegmar** [comment]
Will be handled in 2.0 - see
https://github.com/osiegmar/FastCSV/blob/05046c0a161d946224f9c7c1cf96fb47bb242bc0/src/main/java/de/siegmar/fastcsv/reader/CsvReaderBuilder.java#L124
